name = "bg-remover-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
REMOVE_BG_API_KEY = "9CjVngNHq9FwezUA3xtCBYVj"

[[d1_databases]]
binding = "DB"
database_name = "bg-remover-db"
database_id = "ddd90e1b-d269-447b-824f-a3e320b7fa92"
